language: node_js
node_js:
  - "stable"
before_script:
  - psql -c 'create database snacks;' -U postgres
  - psql -c 'create database snacks_test;' -U postgres
script:
  - npm run knex migrate:latest
  - npm run knex seed:run
  - npm test
services:
  - postgresql
env:
  - NODE_ENV="development"
  - NODE_ENV="test"
